### PR TITLE
Solved few issues

### PR DESCRIPTION
**Pull request by dhruvapte26**
Solved issues #72, #44 , #43 . Cheers!
Ethan Hunt

### CODE REVIEW

**Comment by naveenkumarsangi** [comment]
Sorry, but each user is only entitled to solve only one newcomer issue. You've to move to higher difficulty level issues later on. Please roll your changes back and send in a new pull request addressing just one issue. :smile: Thanks for your contribution.

**Comment by dhruvapte26** [comment]
Sure! Plz quash the PR!

**Comment by naveenkumarsangi** [comment]
**Quash?** I don't understand what you mean @the-ethan-hunt.

**Comment by dhruvapte26** [comment]
Quashing means dismissing the PR as useless. It is also refered as
"squashed". We may have a word prob :)

**Comment by naveenkumarsangi** [comment]
That's called closing, per se. Squashing referring to combining two or more commits into one.

**Comment by naveenkumarsangi** [comment]
You could do the closing, yourself, from the GitHub pull request page.

**Comment by dhruvapte26** [comment]
Sure!

**Comment by ananyo2012** [comment]
@the-ethan-hunt You are welcome to open a new PR solving one of these issues.

**Pull request closed without merging**
