### PR TITLE
Add necessary gems for styling and add bootstrap navbar.

### PR DESCRIPTION
**Pull request by ghoshbishakh**
gems and jquery librariers required for styling are added.
jquery-turbolinks us required for proper functioning of the jquery plugins and the document.ready function
add masonary jquery plugin for using in the threadlist part later
nprogress-rails gem provides the ajax progressbar
removed all old scss css

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
well i amended my commits still in the remote repo all 3 commits are visible?

**Comment by ghoshbishakh** [comment]
@ananyo2012 hope i did not break any SEO modifications?

**Comment by ananyo2012** [comment]
yeah no harm to SEO modifications in application.html.But didn't you remove the inline css in the partial i asked?

**Comment by ghoshbishakh** [comment]
oh.. i forgot ill check

**Comment by sonalkr132** [comment]
> well i amended my commits still in the remote repo all 3 commits are visible?

Assuming there is not much difference between 217702 and d4a5950, do following:

```
git diff 217702..d4a5950 # make sure what are the changes
git reset --hard 217702 # head is now at 217702
git reset --soft HEAD^ # head is not at parent of 217702 but keeps the changes made by you between 217702 and its parent in staging area
```

make the changes you made between  217702 and d4a5950. Commit your work and do:

```
git rebase upstream/github_master # upstream is remote url of main github repo
```

Solve merge conflicts and do `git rebase --continue`

**Comment by ghoshbishakh** [comment]
@sonalkr132 I actually amended later commits .. my git log shows 
screenshot from 2015-07-11 00-01-25

**Comment by sonalkr132** [comment]
what is parent of  d4a5950?

**Comment by ghoshbishakh** [comment]
um parent?

**Comment by sonalkr132** [comment]
commit before  d4a5950

**Comment by ghoshbishakh** [comment]
well i just cloned afresh your repo

**Comment by sonalkr132** [comment]
check this:
screenshot from 2015-07-11 00 12 12
parent of  d4a5950 is 2177022b. You don't need 3 commits here. You just need just one after the fresh clone.

**Comment by ghoshbishakh** [comment]
yes thats what i am trying to do. actually what i did was ammend everything on 2177022. so my local repo only shows one commit and github shows 3 commits

**Comment by sonalkr132** [comment]
do `git push origin github_master --force`

**Comment by ghoshbishakh** [comment]
@sonalkr132 oh.. phew.. saved me

**Comment by sonalkr132** [comment]
I wish I could tell you that we are done with commit. So far we have only removed unwanted commits. Now, lets work with missing commits, shall we?

> gems and jquery librariers required for styling are added.
> jquery-turbolinks us required for proper functioning of the jquery plugins and the document.ready function
> add masonary jquery plugin for using in the threadlist part later
> nprogress-rails gem provides the ajax progressbar
> removed all old scss css

Ideally, for each point you mentioned above, you should have added one commit. At least we need to separate all the deleting of old assets with addition of new one. here is what you should do:
Make a new branch so that in case you screw up, your work on github_master stays intact
- `git branch bootstrap`
- `git checkout bootstrap`

Now you are on bootstrap branch
- make a copy of all the files where you have added content
- do reset --hard to the current state of main github repo.
- delete the old assets and add a commit here
- now replace the files you have copied previously with ones in your current working directory (after commit of deleting old assets).
- add a commit and make new PR

**Comment by ghoshbishakh** [comment]
ok ill break them up and resend

**Pull request closed without merging**
