### PR TITLE
Design edits

### PR DESCRIPTION
**Pull request by ananyo2012**
- [x] Modify design of Login Page
- [x] Modify design of Confirmation and Password page
- [x] Modify design of Admin login page
- [x] Modify design of thread box in home page
- [x] Modify design of thread show page
- [x] Fix typos in readme

@sonalkr132 Please review the PR. Screenshots given below

### CODE REVIEW

**Comment by ananyo2012** [comment]
home

**Comment by ananyo2012** [comment]
thread show

**Comment by ananyo2012** [comment]
login

**Comment by ananyo2012** [comment]
password

**Comment by ananyo2012** [comment]
confirmation

**Comment by ananyo2012** [comment]
admin

**Comment by sonalkr132** [comment]
Thanks :+1:

**Pull request merged**
