### PR TITLE
fixes #4 : In home page, the sign up message appears only when user is not logged in.

### LINKED ISSUE #4: Home page asks "Not a member yet?" even when user is signed in (logged in).
When a user is logged in the message "Welcome to our CAT Forum! Not a member yet? Why don't you click on sign up, it will only take a few minutes. You can log in with Facebook too. Browse through the our list of recent threads, We are sure you will find something interesting. " should not be displayed I think.

### PR DESCRIPTION
**Pull request by ghoshbishakh**
In new threads list page check if a user is logged in. If not add a message at the top of the threads list requesting to sign up.But if the user is logged in do not show such message.
Also reindent the new threads listpage - list.html.erb

### CODE REVIEW

**Comment by sonalkr132** [comment]
From next time please use [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing). Also you would want to [sqash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits when you have more commit than you actually need.

**Comment by ananyo2012** [comment]
@sonalkr132 i didn't notice it earlier.Merging this PR removed the micro data changes i made.So will i add them and send it in my PR?

**Comment by sonalkr132** [comment]
Sorry, I think you are talking about schema.org changes? Yeah sure! Go ahead and add them back. 

This would be an ideal example why we need to test every thing :P If there were test which made sure that those tags existed then those tests would have failed upon unintentional removal.

**Comment by ananyo2012** [comment]
yeah that's right.i will add them back with another commit.

**Pull request merged**
