### PR TITLE
Improvements in examples files and Tests

### PR DESCRIPTION
**Pull request by sonalkr132**

### CODE REVIEW

**Comment by sonalkr132** [comment]
@ananyo2012 You shouldn't have any more problem writing tests.

**Comment by ananyo2012** [comment]
@sonalkr132 thanx.can you tell me where i can get more info on travis ci? u removed the letter opener gem.so won't there be problem in sign in during development?

**Comment by sonalkr132** [comment]
There isn't really anything to know about travis. It just runs the .travis.yml file if you have signed up to travis and kept build on. However if you are really interested in knowing everything in detail, you can go through their doc http://docs.travis-ci.com/

> u removed the letter opener gem.so won't there be problem in sign in during development?

I have not removed it, I only placed it in test, development group.

**Comment by ananyo2012** [comment]
oh sorry to say it.i didn't see it properly.

**Pull request merged**
