### PR TITLE
Fixed #48

### LINKED ISSUE #48: Hide Reply form when not logged in
Hi, this is a `newcomer` issue. This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. If you have contributed before, consider leaving this one for someone new, and looking through our other issues with [low](https://github.com/NIT-dgp/cat-forum/labels/difficulty%2Flow) or [medium](https://github.com/NIT-dgp/cat-forum/labels/difficulty%2Fmedium) difficulty. Thanks!

## The Problem
Reply form shows up even when the user isn't logged in. Though it doesn't submit anything if not logged in but it is better to hide the reply form when an user isn't logged in and show a login prompt instead.
 
## Solution
Here is the code for the reply form https://github.com/NIT-dgp/cat-forum/blob/github_master/app/views/new_threads/show.html.erb#L74-L84. You just need to put an `if-else` statement for this part. Use a simple login prompt like **Log in or sign up  to post a reply** in the else part with the login link in the _Log in_ and _Sign up_ text. Here is how to write a `if-else` statement in erb
```ruby
<% if user_signed_in? %>
  reply_form_code_block
<% else %>
  login_prompt_code_block
<% end %>
```
Just replace the `code_block` with the appropriate html code for the reply form and login form as descibed.
## Steps to Fix
- [ ] claim this issue with a comment
- [ ] set up a repository locally and make sure that all tests pass
- [ ] start a pull request (see our Contribution guidelines)
- [ ] fix the issue following the steps above
- [ ] make sure all tests pass with `bundle exec rspec`
- [ ] alert someone via the developers list (see below) to have your pull request merged.

Please contact the [#general](https://gitter.im/NIT-dgp/General) gitter channel or email the mailing list ( nitdopensource@googlegroups.com ) if you have questions!

### PR DESCRIPTION
**Pull request by divyanshumehta**
screenshot from 2016-11-16 11-57-29
The bottom most line is the `bug fix`

### CODE REVIEW

**Comment by ananyo2012** [comment]
@divyanshumehta Sorry for keeping you waiting. Can you make a small change? Can you keep the if statement within the `<div class="col-xs-12 col-md-12 col-lg-12 thread-col">` block since as you can see the line is otherwise padded a little left w.r.t of the reply divs above. Also keep the login prompt message in a `p` tag.

**Comment by ananyo2012** [comment]
Let's dive a little deeper now. Instead of making another commit for changes you can squash the previous commits and amend the commit. So follow these steps
1. `git rebase -i HEAD~2` Here 2 refers the no of commits you are going back. You will see a rebase window appear. There replace the pick word with squash beside  the commits. Then you will be prompted to edit the commit message again. You will see some instructions follow them and replace the previous commit messages by a single commit message. Then save it and you are done squashing.
2. After this make you changes and do `git add filename`
3. After that do `git commit --amend` What this will do is add the added changes in the previous commit itself and you will be again prompted to edit the commit message. I think you don't need to edit the commit message this time so just save it. And you are done
4. Finally while pushing do a `git push -f` this time since you have to force push this time as the commit history is changed now, The `-f` stands for force push.

I hope this will do it. If you face any difficulties please feel free to contact me.

**Comment by ananyo2012** [comment]
@divyanshumehta Please don't put those files in gitignore. They are needed. Also going with some coding conventions please use two spaces as indentation. You can set your tabs to 2 spaces. This after doing your changes do `git add filename`, then do a `git commit --amend`. Then save the commit and then force push

**Comment by ananyo2012** [comment]
@divyanshumehta Please can you ammend the commit message again and just give `Fixed #48` since basically there are no .gitignore changes.

**Comment by ananyo2012** [comment]
Repeat the previous steps again this time without a git add since there is nothing to be added just ammend the commit message

**Comment by divyanshumehta** [comment]
i think this is final and good to merge

**Comment by ananyo2012** [comment]
@divyanshumehta Thanks for your good work on this :smiley: Consider looking into other issues and solving them. You can probably choose an easy or medium difficulty issue this time :blush:

**Comment by divyanshumehta** [comment]
Small steps at a time :stuck_out_tongue_winking_eye: .

**Comment by ananyo2012** [comment]
@divyanshumehta Also use a different branch in case work on some feature or issue like you did in the last PR. That makes amending commits and rebasing a hell lot easier.

**Pull request merged**
