### PR TITLE
SEO changes and authorization

### PR DESCRIPTION
**Pull request by ananyo2012**
Integrated rubocop, issue #8 ,SEO changes include friendly_id, sitemap changes and adding some h1 and h2 tags.tests are pending for issue #8 .

### CODE REVIEW

**Comment by sonalkr132** [comment]
Why on earth would you make 800+ lines change in one commit? -_-

**Comment by ananyo2012** [comment]
actually i had integrated rubocop, so it caused many indentation changes.

**Comment by sonalkr132** [comment]
I am sorry @ananyo2012  this is not acceptable. Did you not watch the git videos I gave you? This doesn't only need multiple commits for each change set but integration of rubocop, addition of friendly_id, changes in siteman and rest are 4 different PRs. 
I believe I had already said that you guys should raise PRs even on branches with work in progress. Github isn't even giving me option to merge it.

**Comment by ananyo2012** [comment]
yeah i didn't update my repo before that.ok i will undo the commit and send it again.

**Comment by sonalkr132** [comment]
Don't worry, it won't much work. You have already done it so now you will only have to copy paste stuff. Make new branches for rubocop, friendly_id, sitemap and header tags. Copy changes you have made here to those branches and raise PR from there. Again, don't copy paste everything and just add one commit in the end. I believe I had shared links of why commits are important. Please read this http://chris.beams.io/posts/git-commit/

Please watch those git essentials videos if you haven't already. They explain it in good detail when you should add a commit.

**Pull request closed without merging**
