### PR TITLE
More SEO improvements

### PR DESCRIPTION
**Pull request by ananyo2012**
Added friendly url to new threads

### CODE REVIEW

**Comment by sonalkr132** [comment]
Do you think you will be able to write some test for it? I think you will need [request specs](https://www.relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec)

**Comment by ananyo2012** [comment]
@sonalkr132 
Please take a look at the commits.I have described them below with the commit hash.
1.Commit 4daa784: Added friendly id to threads
2.Commit 9ac6dc5: Changed sitemap and robots.txt files
3.Commit 16b49ef: Added the security link of hakiri.io to readme file,changed meta description and added h1 and h2 tags to files
4.Commit 5f80b7d: Added some tests to new_thread controller
5.Commit 8132eb2: Added back the micro data changes of schema.org

**Comment by sonalkr132** [comment]
Thanks @ananyo2012. Can you also let me know which tests are missing?

**Comment by ananyo2012** [comment]
I was writing tests for creating new threads and redirecting to the show
page when users were logged in.

**Pull request merged**
